### PR TITLE
Fix `Referer` request header

### LINKED ISSUE #616: Invalid referer header
**Description of the issue**

Due to history handling logic, `referer` header is _always_ set to the current page being loaded.

As on image below I am requesting `/examples` from different page
image

**How to reproduce the issue**

Issue is clearly visible on swup homepage with javascipt enabled (you can compare with JS disabled, what headers are being sent)

Issue is present in v2-v3.

**Issue cause**

I believe that creating history record should be moved after the page fetch. But I haven't studied the rest of the code to fully understand the reasoning behind current implementation.
https://github.com/swup/swup/blob/343319c986d10506b2ee402c17d8b16cf49a5e1a/src/modules/loadPage.ts#L45-L52

**Severity**

Annoyance, one would expect to behave correctly. But can be worked around with custom request setting on `clickLink` event

### PR DESCRIPTION
**Pull request by hirasso**
Fixes #616

**Description**

Right now, the native `Referer` request header always contains the same URL as the requested page, since `fetchPage` is being executed right **after** the URL was updated through `createHistoryRecord`. This PR attempts to fix this behavior by initializing `fetchPage` right **before** updating the URL.

- [x] The PR is submitted to the `master` branch
- [x] The code was linted before pushing (`npm run lint`)
- [x] All tests are passing (`npm run test`)

**Additional information**

Tested this manually, works as expected on my end (correct `Referer` header).

### CODE REVIEW

File: src/modules/loadPage.ts [hunk 1]
```diff
@@ -41,16 +41,16 @@ export function performPageLoad(this: Swup, data: PageLoadOptions) {
 	// start/skip animation
 	const animationPromises = this.leavePage({ event, skipTransition });
 
+	// Load page data
+	const fetchPromise = this.fetchPage(data);
+
 	// create history record if this is not a popstate call (with or without anchor)
 	if (!isHistoryVisit) {
 		createHistoryRecord(url + (this.scrollToElement || ''));
 	}
```
Comment (gmrchk) [inline src/modules/loadPage.ts:50]: It's not related to this PR, and I think the behaviour still works fine since it's a sync code even with he order shuffled in this file (after previous refactoring), but just something to keep in mind... some browsers (like Safari on iPhone) create screenshot of the page which is visible when navigating back. This screenshot is created at the moment of changing the URL with `pushState`, so doing it in the process of transition might lead to page being faded away or similar on the screenshot.

But again, just noting the use case, all good here.

**Review by gmrchk — COMMENTED** [review]
Nice improvement! ~~Just wondering, what do you use the referer for that you noticed it in a first place? Some analytics were wrong?~~ I didn't notice the linked issue. 👍 

Could you add a unit test for this so we can check what headers are used for fetch after using `loadPage`?

**Comment by hirasso** [comment]
@gmrchk I think releasing this without a unit test would be fine – it's a very simple change. WDYT?

**Comment by gmrchk** [comment]
Ups, totally forgot about this one, soory! Yeah let's go ahead and merge it, but in general coverage is good to increased not decrease. While being simple fix, it's also simple to break in a future by just changing some seemigly irrelevant order.

**Comment by hirasso** [comment]
Totally makes sense 🪚 ...if you want to create the unit test I would certainly study it to learn from it :)

**Comment by daun** [comment]
I've pushed two commits. One adds a test for the correct referer header. I made sure it's failing in the current master branch and passing in this one. The other one adds a test for the other request headers, for good measure and since we've never checked for those.

I had to pin the E2E action node version to v16 since `start-server-and-test` is currently stalling with node 18.

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
Wow... Cypress is way over my head. How come everyone always assumes that writing tests is "lame and easy"? Great work @daun !
